package entity;
// Generated Apr 8, 2019 9:05:04 AM by Hibernate Tools 4.3.1

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CanHo generated by hbm2java
 */
@Entity
@Table(name = "canTable")
public class CanHo implements java.io.Serializable {

    private String canHoId;
    private String maSoCanHo;
    private String khachHangId;
    
    //dkm 
    private ThongTinKhachHang khachHang; // truong nay se luu du lieu ben KHDAO
    private Short tang;
    private Set<ThongTinKhachHang> thongTinKhachHangs = new HashSet<ThongTinKhachHang>(0);
    private Set<HoaDonInternet> hoaDonInternets = new HashSet<HoaDonInternet>(0);
    private Set<HoaDonDichVu> hoaDonDichVus = new HashSet<HoaDonDichVu>(0);
    private Set<HoaDonSinhHoat> hoaDonSinhHoats = new HashSet<HoaDonSinhHoat>(0);
   

    public CanHo() {
    }

    public CanHo(String canHoId) {
        this.canHoId = canHoId;
    }

    public CanHo(String canHoId, String maSoCanHo, String khachHangId, Short tang, Set<ThongTinKhachHang> thongTinKhachHangs, Set<HoaDonInternet> hoaDonInternets, Set<HoaDonDichVu> hoaDonDichVus, Set<HoaDonSinhHoat> hoaDonSinhHoats) {
        this.canHoId = canHoId;
        this.maSoCanHo = maSoCanHo;
        this.khachHangId = khachHangId;
        this.tang = tang;
        this.thongTinKhachHangs = thongTinKhachHangs;
        this.hoaDonInternets = hoaDonInternets;
        this.hoaDonDichVus = hoaDonDichVus;
        this.hoaDonSinhHoats = hoaDonSinhHoats;
    }

    public ThongTinKhachHang getKhachHang() {
        return khachHang;
    }

    public void setKhachHang(ThongTinKhachHang khachHang) {
        this.khachHang = khachHang;
    }

    @Column(name = "canhoid")
    @Id
    public String getCanHoId() {
        return this.canHoId;
    }

    public void setCanHoId(String canHoId) {
        this.canHoId = canHoId;
    }

    public String getMaSoCanHo() {
        return this.maSoCanHo;
    }

    public void setMaSoCanHo(String maSoCanHo) {
        this.maSoCanHo = maSoCanHo;
    }

    public String getKhachHangId() {
        return this.khachHangId;
    }

    public void setKhachHangId(String khachHangId) {
        this.khachHangId = khachHangId;
    }

    public Short getTang() {
        return this.tang;
    }

    public void setTang(Short tang) {
        this.tang = tang;
    }

    public Set<ThongTinKhachHang> getThongTinKhachHangs() {
        return this.thongTinKhachHangs;
    }

    public void setThongTinKhachHangs(Set<ThongTinKhachHang> thongTinKhachHangs) {
        this.thongTinKhachHangs = thongTinKhachHangs;
    }

    public Set<HoaDonInternet> getHoaDonInternets() {
        return this.hoaDonInternets;
    }

    public void setHoaDonInternets(Set<HoaDonInternet> hoaDonInternets) {
        this.hoaDonInternets = hoaDonInternets;
    }

    public Set<HoaDonDichVu> getHoaDonDichVus() {
        return this.hoaDonDichVus;
    }

    public void setHoaDonDichVus(Set<HoaDonDichVu> hoaDonDichVus) {
        this.hoaDonDichVus = hoaDonDichVus;
    }

    public Set<HoaDonSinhHoat> getHoaDonSinhHoats() {
        return this.hoaDonSinhHoats;
    }

    public void setHoaDonSinhHoats(Set<HoaDonSinhHoat> hoaDonSinhHoats) {
        this.hoaDonSinhHoats = hoaDonSinhHoats;
    }

  

}
