package entity;
// Generated Apr 8, 2019 9:05:04 AM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;

/**
 * HoaDonSinhHoat generated by hbm2java
 */
public class HoaDonSinhHoat  implements java.io.Serializable {


     private int hoaDonSinhHoatId;
     private CanHo canHo;
     private Date ngayThang;
     private String maHddien;
     private Integer chiSoDienBanDau;
     private Integer chiSoDienCuoi;
     private Double tienDien;
     private String maHdnuoc;
     private Integer chiSoNuocBanDau;
     private Integer chiSoNuocCuoi;
     private Double tienNuoc;

    public HoaDonSinhHoat() {
    }

	
    public HoaDonSinhHoat(int hoaDonSinhHoatId) {
        this.hoaDonSinhHoatId = hoaDonSinhHoatId;
    }
    public HoaDonSinhHoat(int hoaDonSinhHoatId, CanHo canHo, Date ngayThang, String maHddien, Integer chiSoDienBanDau, Integer chiSoDienCuoi, Double tienDien, String maHdnuoc, Integer chiSoNuocBanDau, Integer chiSoNuocCuoi, Double tienNuoc) {
       this.hoaDonSinhHoatId = hoaDonSinhHoatId;
       this.canHo = canHo;
       this.ngayThang = ngayThang;
       this.maHddien = maHddien;
       this.chiSoDienBanDau = chiSoDienBanDau;
       this.chiSoDienCuoi = chiSoDienCuoi;
       this.tienDien = tienDien;
       this.maHdnuoc = maHdnuoc;
       this.chiSoNuocBanDau = chiSoNuocBanDau;
       this.chiSoNuocCuoi = chiSoNuocCuoi;
       this.tienNuoc = tienNuoc;
    }
   
    public int getHoaDonSinhHoatId() {
        return this.hoaDonSinhHoatId;
    }
    
    public void setHoaDonSinhHoatId(int hoaDonSinhHoatId) {
        this.hoaDonSinhHoatId = hoaDonSinhHoatId;
    }
    public CanHo getCanHo() {
        return this.canHo;
    }
    
    public void setCanHo(CanHo canHo) {
        this.canHo = canHo;
    }
    public Date getNgayThang() {
        return this.ngayThang;
    }
    
    public void setNgayThang(Date ngayThang) {
        this.ngayThang = ngayThang;
    }
    public String getMaHddien() {
        return this.maHddien;
    }
    
    public void setMaHddien(String maHddien) {
        this.maHddien = maHddien;
    }
    public Integer getChiSoDienBanDau() {
        return this.chiSoDienBanDau;
    }
    
    public void setChiSoDienBanDau(Integer chiSoDienBanDau) {
        this.chiSoDienBanDau = chiSoDienBanDau;
    }
    public Integer getChiSoDienCuoi() {
        return this.chiSoDienCuoi;
    }
    
    public void setChiSoDienCuoi(Integer chiSoDienCuoi) {
        this.chiSoDienCuoi = chiSoDienCuoi;
    }
    public Double getTienDien() {
        return this.tienDien;
    }
    
    public void setTienDien(Double tienDien) {
        this.tienDien = tienDien;
    }
    public String getMaHdnuoc() {
        return this.maHdnuoc;
    }
    
    public void setMaHdnuoc(String maHdnuoc) {
        this.maHdnuoc = maHdnuoc;
    }
    public Integer getChiSoNuocBanDau() {
        return this.chiSoNuocBanDau;
    }
    
    public void setChiSoNuocBanDau(Integer chiSoNuocBanDau) {
        this.chiSoNuocBanDau = chiSoNuocBanDau;
    }
    public Integer getChiSoNuocCuoi() {
        return this.chiSoNuocCuoi;
    }
    
    public void setChiSoNuocCuoi(Integer chiSoNuocCuoi) {
        this.chiSoNuocCuoi = chiSoNuocCuoi;
    }
    public Double getTienNuoc() {
        return this.tienNuoc;
    }
    
    public void setTienNuoc(Double tienNuoc) {
        this.tienNuoc = tienNuoc;
    }




}


