package entity;
// Generated Apr 8, 2019 9:05:04 AM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;

/**
 * HoaDonInternet generated by hbm2java
 */
public class HoaDonInternet  implements java.io.Serializable {


     private String hoaDonInternetId;
     private CanHo canHo;
     private Date ngayThang;
     private Double tien;

    public HoaDonInternet() {
    }

	
    public HoaDonInternet(String hoaDonInternetId) {
        this.hoaDonInternetId = hoaDonInternetId;
    }
    public HoaDonInternet(String hoaDonInternetId, CanHo canHo, Date ngayThang, Double tien) {
       this.hoaDonInternetId = hoaDonInternetId;
       this.canHo = canHo;
       this.ngayThang = ngayThang;
       this.tien = tien;
    }
   
    public String getHoaDonInternetId() {
        return this.hoaDonInternetId;
    }
    
    public void setHoaDonInternetId(String hoaDonInternetId) {
        this.hoaDonInternetId = hoaDonInternetId;
    }
    public CanHo getCanHo() {
        return this.canHo;
    }
    
    public void setCanHo(CanHo canHo) {
        this.canHo = canHo;
    }
    public Date getNgayThang() {
        return this.ngayThang;
    }
    
    public void setNgayThang(Date ngayThang) {
        this.ngayThang = ngayThang;
    }
    public Double getTien() {
        return this.tien;
    }
    
    public void setTien(Double tien) {
        this.tien = tien;
    }




}


