package entity;
// Generated Apr 8, 2019 9:05:04 AM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * HoaDonDichVu generated by hbm2java
 */
public class HoaDonDichVu  implements java.io.Serializable {


     private String hoaDonDichVuId;
     private CanHo canHo;
     private Users users;
     private Double tienDichVuCoBan;
     private Double tienGuiXe;
     private Double tongTien;
     private Date thang;
     private Set<GuiXe> guiXes = new HashSet<GuiXe>(0);

    public HoaDonDichVu() {
    }

	
    public HoaDonDichVu(String hoaDonDichVuId) {
        this.hoaDonDichVuId = hoaDonDichVuId;
    }
    public HoaDonDichVu(String hoaDonDichVuId, CanHo canHo, Users users, Double tienDichVuCoBan, Double tienGuiXe, Double tongTien, Date thang, Set<GuiXe> guiXes) {
       this.hoaDonDichVuId = hoaDonDichVuId;
       this.canHo = canHo;
       this.users = users;
       this.tienDichVuCoBan = tienDichVuCoBan;
       this.tienGuiXe = tienGuiXe;
       this.tongTien = tongTien;
       this.thang = thang;
       this.guiXes = guiXes;
    }
   
    public String getHoaDonDichVuId() {
        return this.hoaDonDichVuId;
    }
    
    public void setHoaDonDichVuId(String hoaDonDichVuId) {
        this.hoaDonDichVuId = hoaDonDichVuId;
    }
    public CanHo getCanHo() {
        return this.canHo;
    }
    
    public void setCanHo(CanHo canHo) {
        this.canHo = canHo;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public Double getTienDichVuCoBan() {
        return this.tienDichVuCoBan;
    }
    
    public void setTienDichVuCoBan(Double tienDichVuCoBan) {
        this.tienDichVuCoBan = tienDichVuCoBan;
    }
    public Double getTienGuiXe() {
        return this.tienGuiXe;
    }
    
    public void setTienGuiXe(Double tienGuiXe) {
        this.tienGuiXe = tienGuiXe;
    }
    public Double getTongTien() {
        return this.tongTien;
    }
    
    public void setTongTien(Double tongTien) {
        this.tongTien = tongTien;
    }
    public Date getThang() {
        return this.thang;
    }
    
    public void setThang(Date thang) {
        this.thang = thang;
    }
    public Set<GuiXe> getGuiXes() {
        return this.guiXes;
    }
    
    public void setGuiXes(Set<GuiXe> guiXes) {
        this.guiXes = guiXes;
    }




}


