package entity;
// Generated Apr 8, 2019 9:05:04 AM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private String userId;
     private String pass;
     private Serializable ten;
     private Serializable email;
     private Serializable soDt;
     private Set<HoaDonDichVu> hoaDonDichVus = new HashSet<HoaDonDichVu>(0);

    public Users() {
    }

	
    public Users(String userId) {
        this.userId = userId;
    }
    public Users(String userId, String pass, Serializable ten, Serializable email, Serializable soDt, Set<HoaDonDichVu> hoaDonDichVus) {
       this.userId = userId;
       this.pass = pass;
       this.ten = ten;
       this.email = email;
       this.soDt = soDt;
       this.hoaDonDichVus = hoaDonDichVus;
    }
   
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }
    public Serializable getTen() {
        return this.ten;
    }
    
    public void setTen(Serializable ten) {
        this.ten = ten;
    }
    public Serializable getEmail() {
        return this.email;
    }
    
    public void setEmail(Serializable email) {
        this.email = email;
    }
    public Serializable getSoDt() {
        return this.soDt;
    }
    
    public void setSoDt(Serializable soDt) {
        this.soDt = soDt;
    }
    public Set<HoaDonDichVu> getHoaDonDichVus() {
        return this.hoaDonDichVus;
    }
    
    public void setHoaDonDichVus(Set<HoaDonDichVu> hoaDonDichVus) {
        this.hoaDonDichVus = hoaDonDichVus;
    }




}


